### ISSUE TITLE
Image License Compliance

### ISSUE THREAD

**Issue by ChristopherJMiller** [cameron-keene/ACE_Website#5]
Just double checking image license compliance with a couple of your images:

This vector image,
https://github.com/UF-ACE/ACE_Website/blob/master/src/features/background.png

which appears to be from adobe stock,
https://stock.adobe.com/175336214?asset_id=175336214

Would not be under any creative commons license and therefore can't be used unless you paid for the license.

Additionally this one,
https://github.com/UF-ACE/ACE_Website/blob/master/src/imgs/stock-vector-a-stream-of-binary-matrix-code-on-the-screen-numbers-of-the-computer-matrix-the-concept-of-coding-1043394892.jpeg

Which appears to be from shutterstock given the watermark would be under the same restrictions.

And additionally this one,
https://github.com/UF-ACE/ACE_Website/blob/master/src/features/4498903.jpg

which appears to be from freepik which requires explicit attribution:
https://www.freepik.com/free-vector/code-typing-concept-illustration_10594781.htm

I would recommend swapping them out for images under a creative commons based license, ideally cc0. Pexels is a good resource for that: https://www.pexels.com/creative-commons-images/

**Comment by charlieforward9** [comment]
Wrapped this up, and sent the illegal images to the garbo. Thank you. Any other bugs that we added since you added these? @ChristopherJMiller
