### ISSUE TITLE
Transfer Backend from Firebase to MongoDB

### ISSUE THREAD

**Issue by cameron-keene** [cameron-keene/ACE_Website#6]
Need to transfer backend from Firebase to MongoDB, due to security concerns.

**Comment by ChristopherJMiller** [comment]
in case mongo is looking like a pain to transition to/hosting is a concern, given how officers are only updated once a year it might be better for the longevity of the site to have the officers just defined within a json file, bundle that with the build, and load that in like an api call that way it's also more portable depending on how you want to host it (and better yet, github pages all-in-one compatible).

However, if you're using this as an opportunity to learn, have at it!
